config/routes.rb
Rails.application.routes.draw do
  get 'matcher/new'
  get 'matcher/show'

  root 'matcher#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matcher_controller.rb
class MatcherController < ApplicationController
  def new
    @first_name = params[:first_name].presence
    @second_name = params[:second_name].presence
  end

  def show
    @first_name = params[:matcher][:first_name].strip.titleize.presence || 'Ricardão'
    @second_name = params[:matcher][:second_name].strip.titleize.presence || 'Cremosa'

    key = [@first_name, @second_name].sort.sum
    time_together = calculate_time(key).zero? ? 1 : calculate_time(key)

    @years = time_together / 360
    @months = (time_together - 360 * @years) / 30
    @days = (time_together - 360 * @years) % 30
  end

  # Try to get first 4 numbers of generated hash
  def calculate_time(key)
    @calculate_time ||= Digest::SHA256.hexdigest(key)[/(\d{1,4})/, 1].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matcher_helper.rb
module MatcherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tempo Juntos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="_AX2eu-iGv1ZYNCjFqm2QU0Y6NO-oa8_xQiwtlVL4D8" />
    <meta name="description" content="Descubra quanto tempo juntos duas pessoas ficariam se começassem um relacionamento neste exato momento. Digite o nome da primeira e segunda pessoa e calcule quanto tempo juntos ficariam."/>
    <%= favicon_link_tag %>
    <meta name="theme-color" content="#ffffff">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110873033-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-110873033-1');
    </script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-7401580444189328",
        enable_page_level_ads: true
      });
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matcher/new.html.erb
<div class="container-fluid col-md-4 matcher">
  <div class="row-fluid">
    <div class="centering text-center">
      <h1 class="h4">TEMPO JUNTOS</h1>
      <%= form_for :matcher, url: matcher_show_url, method: :get, enforce_utf8: false do |form| %>
        <div class="form-row form-row-new">
          <div class="col">
            <%= form.text_field :first_name, value: @first_name, placeholder: '1ª pessoa', class: 'form-control' %>
          </div>
          <div class="col"></div>
          <div class="col">
            <%= form.text_field :second_name, value: @second_name, placeholder: '2ª pessoa', class: 'form-control'  %>
          </div>
        </div>
        <p><%= form.submit 'Calcular', class: 'btn btn-secondary btn-lg'%></p>
      <% end  %>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/matcher/show.html.erb
<%
time_together = ''

if @years > 0
  time_together += pluralize(@years, 'ano ', 'anos ')
end

if @months > 0
  if @years > 0
    time_together += 'e '
  end
  time_together += pluralize(@months, 'mês ', 'meses ')
end

if @days > 0
  if @years > 0 || @months > 0
    time_together += 'e '
  end
  time_together += pluralize(@days, 'dia ', 'dias ')
end

share_message = "O tempo que #{@first_name} e #{@second_name} ficariam caso se relacionassem hoje é de #{time_together}"
%>
<div class="container-fluid col-md-6 matcher">
  <div class="row-fluid">
    <div class="centering text-center centering-show">
      <h1 class="h2 show-names"><%= @first_name %> & <%= @second_name %></h1>
      <div class="result">
        <div class="form-row">
          <div class="col"><%= @years > 1 ? 'Anos' : 'Ano' %></div>
          <div class="col"><%= @months > 1 ? 'Meses' : 'Mês' %></div>
          <div class="col"><%= @days > 1 ? 'Dias' : 'Dia' %></div>
        </div>
        <div class="form-row">
          <div class="col"><%= @years %></div>
          <div class="col"><%= @months %></div>
          <div class="col"><%= @days %></div>
        </div>
      </div>
      <%= social_share_button_tag(share_message, desc: share_message) %>
      <br>
      <p><%= link_to "Calcular novamente", matcher_new_url(first_name: @first_name, second_name: @second_name), class: 'btn btn-secondary' %></p>
    </div>
  </div>
</div>